### ISSUE TITLE
Add support for Rasberry Pi V.1

### ISSUE THREAD

**Issue by blu-IT** [P2PVPS/p2pvps-client#10]
Hi,

I run the simple-client installation like mentioned here and arriving at this point (4) had some problems:

`curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -`

Because of Raspberry Pi V.1 (arm6) I had to install node manually. 
No problem, did it like this:

wget https://nodejs.org/dist/latest/node-v10.5.0-linux-armv6l.tar.gz
tar -xvf node-v10.5.0-linux-armv6l.tar.gz
cd node-v10.5.0-linux-armv6l
sudo cp -R * /usr/local/

OK, installation went on fine until point 15:

`node p2p-vps-client.js`

The script ( I think it is write-files.js ) starts and runs the first steps successfully, but then stops at the same point with the same message mention before (4) and I tried modifing the write-files.js script changing the node install part like mentioned above - but this time no luck!
So I can't get a docker instance running until now, without solving that issue. Don't think it should be a big coding problem?

Thanks!

Regards

**Comment by christroutner** [comment]
Good feedback. The P2P VPS client software depends on Docker, and I wasn't aware that Docker could run on the RPi v1. So even if you get past this point, I'm not sure if that part will work.

I also notice that you installed node v10 from source. The code has only been tested with node v8 at this point. v10 should work, but it's untested and may be the source of the problem.

What was the error message you were getting?

**Comment by blu-IT** [comment]
OK, maybe Docker won't run on RPi v1 - I didn't know that. Thanks for the hint.
But I'll give ist a try ;-)

I run this script (before editing "write-files.js")

`node p2p-vps-client.js`

and at stage 12 of 33 it brings this message (like already mention above at step 4 and I could solve by installing node manually):

```
## Installing the NodeSource Node.js 8.x LTS Carbon repo...

## You appear to be running on ARMv6 hardware. Unfortunately this is not currently supported by the NodeSource Linux distributions. Please use the 'linux-armv6l' binary tarballs available directly from nodejs.org for Node.js 4 and later.
```

followed by this message:

```
The command '/bin/sh -c bash nodesource_setup.sh' returned a non-zero code: 1
Error while trying to build Docker image! { Error: Command failed: ./lib/buildImage
    at Promise.all.then.arr (/home/pi/p2pvps-client/client/rpi/simple/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  killed: false,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: './lib/buildImage',
  timedOut: false }
Error while trying to build Docker image! [ { Error: Command failed: ./lib/buildImage
      at Promise.all.then.arr (/home/pi/p2pvps-client/client/rpi/simple/node_modules/execa/index.js:236:11)
      at process._tickCallback (internal/process/next_tick.js:68:7)
    code: 1,
    killed: false,
    stdout: null,
    stderr: null,
    failed: true,
    signal: null,
    cmd: './lib/buildImage',
    timedOut: false } ]
error: Error while trying to build Docker image! code=1, killed=false, stdout=null, stderr=null, failed=true, signal=null, cmd=./lib/buildImage, timedOut=false
{
  "code": 1,
  "killed": false,
  "stdout": null,
  "stderr": null,
  "failed": true,
  "signal": null,
  "cmd": "./lib/buildImage",
  "timedOut": false
} []
error: {
  "code": 1,
  "killed": false,
  "stdout": null,
  "stderr": null,
  "failed": true,
  "signal": null,
  "cmd": "./lib/buildImage",
  "timedOut": false
}
```

So thought I can modify the script and repeat the steps I did on step 4 of the client install. 
I tried to edit `write-files.js` with these lines:

```
#RUN curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
#RUN bash nodesource_setup.sh
RUN wget https://nodejs.org/dist/latest/node-v10.5.0-linux-armv6l.tar.gz
RUN tar -xvf node-v10.5.0-linux-armv6l.tar.gz
RUN cd node-v10.5.0-linux-armv6l
RUN sudo cp -R * /usr/local/
```

But it ended up in a mess :-)))

Regards

**Comment by christroutner** [comment]
That's exactly what I would have recommended you do. It looks like Docker is building and running. It's just having trouble getting node installed into the container.

**Comment by christroutner** [comment]
The `sudo` command on the last line might be the problem.

What's the error you're getting when the Docker container fails the build?

**Comment by blu-IT** [comment]
Deleted sudo and the script stops here:

```
Step 11/33 : RUN wget https://nodejs.org/dist/latest/node-v10.5.0-linux-armv6l.tar.gz
 ---> Running in 38ce5a82e1d4
/bin/sh: 1: wget: not found
The command '/bin/sh -c wget https://nodejs.org/dist/latest/node-v10.5.0-linux-armv6l.tar.gz' returned a non-zero code: 127
Error while trying to build Docker image! { Error: Command failed: ./lib/buildImage
    at Promise.all.then.arr (/home/pi/p2pvps-client/client/rpi/simple/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 127,
  killed: false,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: './lib/buildImage',
  timedOut: false }
Error while trying to build Docker image! [ { Error: Command failed: ./lib/buildImage
      at Promise.all.then.arr (/home/pi/p2pvps-client/client/rpi/simple/node_modules/execa/index.js:236:11)
      at process._tickCallback (internal/process/next_tick.js:68:7)
    code: 127,
    killed: false,
    stdout: null,
    stderr: null,
    failed: true,
    signal: null,
    cmd: './lib/buildImage',
    timedOut: false } ]
error: Error while trying to build Docker image! code=127, killed=false, stdout=null, stderr=null, failed=true, signal=null, cmd=./lib/buildImage, timedOut=false
{
  "code": 127,
  "killed": false,
  "stdout": null,
  "stderr": null,
  "failed": true,
  "signal": null,
  "cmd": "./lib/buildImage",
  "timedOut": false
} []
error: {
  "code": 127,
  "killed": false,
  "stdout": null,
  "stderr": null,
  "failed": true,
  "signal": null,
  "cmd": "./lib/buildImage",
  "timedOut": false
}
root@raspberrypi:/home/pi/p2pvps-client/client/rpi/simple#
```

**Comment by blu-IT** [comment]
OK, so thinking about the script more clearly ;-) there should be _wget_ and _tar_ installed on the docker image before trying to install _node_ - right?

So maybe this should be modified here before?
https://github.com/P2PVPS/server-deployment2/blob/master/sshd-container/Dockerfile

**Comment by christroutner** [comment]
Yes. You beat me to it. 

Except this is the file you should edit (assuming you're running the simple client):
https://github.com/P2PVPS/p2pvps-client/blob/master/client/rpi/simple/lib/write-files.js

These lines:
```
...
RUN echo "export VISIBLE=now" >> /etc/profile
RUN curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
RUN bash nodesource_setup.sh
RUN apt-get install -y nodejs
RUN apt-get install -y build-essential
RUN apt-get install -y inetutils-ping
...
```

Should look more like these lines:
```
...
RUN echo "export VISIBLE=now" >> /etc/profile
#RUN curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
#RUN bash nodesource_setup.sh
#RUN apt-get install -y nodejs
RUN apt-get install -y wget tar
RUN wget https://nodejs.org/dist/latest/node-v10.5.0-linux-armv6l.tar.gz
RUN tar -xvf node-v10.5.0-linux-armv6l.tar.gz
RUN cd node-v10.5.0-linux-armv6l
RUN cp -R * /usr/local/
RUN apt-get install -y build-essential
RUN apt-get install -y inetutils-ping
...
```

**Comment by blu-IT** [comment]
Yeah, did it and had to run it serveral times, because it stoped at different stages.
E.g. when running _tar_ it told me, that the directory was renamed (?!). But after starting the script for the third time, it unpacked everything but stops now at the step, when doing

`RUN cp -R * /usr/local/`

with this error:

```
Step 16/35 : RUN cp -R * /usr/local/
 ---> Running in 61e7ab9b0fd4
cp: error reading ‘proc/1/task/1/mem’: Input/output error
cp: failed to extend ‘/usr/local/proc/1/task/1/mem’: Input/output error
cp: error reading ‘proc/1/task/1/clear_refs’: Invalid argument
cp: failed to extend ‘/usr/local/proc/1/task/1/clear_refs’: Invalid argument
cp: error reading ‘proc/1/mem’: Input/output error
cp: failed to extend ‘/usr/local/proc/1/mem’: Input/output error
cp: error reading ‘proc/1/clear_refs’: Invalid argument
cp: failed to extend ‘/usr/local/proc/1/clear_refs’: Invalid argument
cp: error reading ‘proc/1/timerslack_ns’: Operation not permitted
cp: failed to extend ‘/usr/local/proc/1/timerslack_ns’: Operation not permitted
cp: cannot stat ‘proc/5/task/5/fd/3’: No such file or directory
cp: cannot stat ‘proc/5/task/5/fdinfo/3’: No such file or directory
cp: error reading ‘proc/5/task/5/mem’: Input/output error
cp: failed to extend ‘/usr/local/proc/5/task/5/mem’: Input/output error
cp: error reading ‘proc/5/task/5/clear_refs’: Invalid argument
cp: failed to extend ‘/usr/local/proc/5/task/5/clear_refs’: Invalid argument
cp: cannot stat ‘proc/5/fd/3’: No such file or directory
cp: cannot stat ‘proc/5/fdinfo/3’: No such file or directory
cp: error reading ‘proc/5/mem’: Input/output error
cp: failed to extend ‘/usr/local/proc/5/mem’: Input/output error
cp: error reading ‘proc/5/clear_refs’: Invalid argument
cp: failed to extend ‘/usr/local/proc/5/clear_refs’: Invalid argument
cp: cannot open ‘proc/sys/net/ipv4/route/flush’ for reading: Permission denied
cp: error reading ‘proc/sys/net/ipv6/conf/all/stable_secret’: Input/output error
cp: failed to extend ‘/usr/local/proc/sys/net/ipv6/conf/all/stable_secret’: Input/output error
cp: error reading ‘proc/sys/net/ipv6/conf/default/stable_secret’: Input/output error
cp: failed to extend ‘/usr/local/proc/sys/net/ipv6/conf/default/stable_secret’: Input/output error
cp: error reading ‘proc/sys/net/ipv6/conf/eth0/stable_secret’: Input/output error
cp: failed to extend ‘/usr/local/proc/sys/net/ipv6/conf/eth0/stable_secret’: Input/output error
cp: error reading ‘proc/sys/net/ipv6/conf/lo/stable_secret’: Input/output error
cp: failed to extend ‘/usr/local/proc/sys/net/ipv6/conf/lo/stable_secret’: Input/output error
cp: cannot open ‘proc/sys/net/ipv6/route/flush’ for reading: Permission denied
cp: cannot open ‘proc/sys/vm/compact_memory’ for reading: Permission denied
cp: cannot open ‘proc/kmsg’ for reading: Operation not permitted
cp: error reading ‘proc/sysrq-trigger’: Input/output error
cp: failed to extend ‘/usr/local/proc/sysrq-trigger’: Input/output error
^C
```

I'm not sure if this is a issue with my Rpi installation...

**Comment by christroutner** [comment]
Hmm. The permission errors are odd. Try adding the `sudo`  back into that command and see if helps.

**Comment by blu-IT** [comment]
Yes, already tried adding sudo... no change, same errors.

**Comment by christroutner** [comment]
Hmm. Frustrating.

There is apparently something going wrong with the build of node, but without a RPi v1 I can't really duplicate the issue.

**Comment by blu-IT** [comment]
Ok, don't mind. Hopefully I will do a clean install of the RPi in the next days and have another try. 
If yout don't mind, leave this issue open and I will give a feedback in the next days.

Thanks for your effort!
